name: dotnet package

on: [push]

jobs:
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet user-secrets set "ServiceApiKey" "${{ secrets.APIKEY }}"
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        env:
            ASPNETCORE_URLS: "https://+;http://+"
        run: dotnet publish -c Release -o /home/pi/web
