name: dotnet package

on: [push]

jobs:
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish -c Release -o ~/web/house-dashboard-server
      - name: Start service
        run: | 
          systemctl daemon-reload
          systemctl restart house-dashboard-server
